# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TAEUK WIKI
subtitle: Javascript Library
description: For Memory
keywords: Javascript
author: Taeuk Kang
language: ko
timezone: Asia/Seoul

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://taeuk-gang.github.io
root: /
# permalink: :year/:month/:day/:title/
permalink: wiki/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - '_posts/**/embed_page/**'
  - 'presentation/**/*.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
## Markdown
## https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true # GitHub flavored markdown 지원
  pedantic: false # 오리지널 마크다운 사용
  sanitize: false # HTML 무시
  tables: true # GFM 테이블 지원
  breaks: true # GFM
  smartLists: true # 오리지널 마크다운보다 스마트한 리스트
  smartypants: true # Use "smart" typograhic punctuation for things like quotes and dashes.
  modifyAnchors: '' # Use for transform anchorIds. if 1 to lowerCase and if 2 to upperCase.
  autolink: true # 오토링크 지원. 텍스트에서 링크를 자동으로 인식.

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Wikitten

## Plugins: https://hexo.io/plugins/
### JsonContent
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html
    
### Creat sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/taeuk-gang/taeuk-gang.github.io.git
  branch: master
  token: $GITHUB_TOKEN
hide_posts:
  # Change the filter name to fit your need
  filter: secret
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: []
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: true